Squashed 'modelscripts/' changes from 79fd261..8138733
8138733 Fix default nml ref path in checknml/diffnml
bad8194 Update version and dep
d0bd3a4 Add nml ref and updater data for 5.0.rc1 and rc2
14c82d0 Scripts update for monorepos/fullcode

git-subtree-dir: modelscripts
git-subtree-split: 813873377abb3f4a86bba7479d16f00059e4276f

diff --git a/bin/checknml2 b/bin/checknml2
--- a/bin/checknml2
+++ b/bin/checknml2
@@ -30,6 +30,12 @@ EOF
 
 refmode=0
 reffile=${ATM_MODEL_DFILES}/nml/ref/gem_settings.${ATM_MODEL_VERSION}.ref
+if [[ ! -f ${reffile} ]] ; then
+   mypath="$(which r.config_modelscripts_all 2>/dev/null || true)"
+   if [[ "x${mypath}" != "x" && -f ${mypath:-NO_SUCH_FILE}  ]] ; then
+      reffile=${mypath%/*}/../share/nml_updater/ref/gem_settings.${ATM_MODEL_VERSION}.ref
+   fi
+fi
 nmlfiles=""
 nml=""
 myverb=""
@@ -58,8 +64,13 @@ while [[ $# -gt 0 ]] ; do
 done
 nmlfiles="${nmlfiles} $@"
 
-if [[ x"${nmlfiles}" == x"" ]] ; then
+if [[ x"${nmlfiles}" == x" " ]] ; then
    nmlfiles="./gem_settings.nml"
+fi
+
+if [[ ! -f ${nmlfiles# } ]] ; then
+   echo "ERROR: cannot find ${nmlfiles}" 2>&1
+   exit 1
 fi
 
 
@@ -68,7 +79,8 @@ if [[ $refmode == 1 ]] ; then
 fi
 
 if [[ ! -f ${reffile:-/NO/SUCH/FILE} ]] ; then
-   myerror "Reference nml file should exists and does not: ${reffile:-/NO/SUCH/FILE}"
+   myerror "Reference nml file should exists and does not: ${reffile:-/NO/SUCH/FILE}
+       Try with: ${MYSELF} ${myverb} ${checktypes} ${nml} -r -- ${nmlfiles}"
 fi
 
 status=0
